vcf <- open_vcf("inst/test.vcf.gz")
vars <- read_vars(vcf, n=10)
vars <- read_vars(vcf, n=10, info_keys=c("AF","AC"), format_keys=c("GT","AD","DP"), format_keys_exclude=c("PL"))
vars <- read_vars(vcf, n=10, info_keys=c("AF","AC"), format_keys=c("GT","AD","DP"), format_keys_exclude=c("PL"), split_info=T)
vars <- read_vars(vcf, n=10, info_keys=c("AF","AC"), format_keys=c("GT","AD","DP"), format_keys_exclude=c("PL"), split_info=T, split_format=T)
vars <- read_vars(vcf, n=10, info_keys=c("AF","AC"), format_keys_exclude=c("PL"), split_info=T, split_format=T)
vars <- read_vars("inst/test.vcf.gz")
dim(vars)
vars <- read_vars("inst/test.vcf.gz", break_alt=T)
dim(vars)

vars <- read_vars("inst/test.vcf.gz", break_alt=T, split_info=T)
dim(vars)

vars <- read_vars("inst/test.vcf.gz", break_alt=T, split_info=T, split_format=T)
dim(vars)
